eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/
spring:
  application:
    name: feign-dome
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/1708b?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    api-log:
      path: /api-log/**
      serviceId: provider-demo
